//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.4952
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsProgram.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągw itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwrz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmsProgram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadkw przeszukiwania zasobw za pomocą tej klasy zasobw wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CampaignAddMenu {
            get {
                object obj = ResourceManager.GetObject("CampaignAddMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CampaignEditMenu {
            get {
                object obj = ResourceManager.GetObject("CampaignEditMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CampaignPauseMenu {
            get {
                object obj = ResourceManager.GetObject("CampaignPauseMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CampaignSendOneSmsMenu {
            get {
                object obj = ResourceManager.GetObject("CampaignSendOneSmsMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CampaignStartMenu {
            get {
                object obj = ResourceManager.GetObject("CampaignStartMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CampaignTemplateMenu {
            get {
                object obj = ResourceManager.GetObject("CampaignTemplateMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditAddNewMenu {
            get {
                object obj = ResourceManager.GetObject("EditAddNewMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditCopyMenu {
            get {
                object obj = ResourceManager.GetObject("EditCopyMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditCutMenu {
            get {
                object obj = ResourceManager.GetObject("EditCutMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditDeleteMenu {
            get {
                object obj = ResourceManager.GetObject("EditDeleteMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditLookupMenu {
            get {
                object obj = ResourceManager.GetObject("EditLookupMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditPasteMenu {
            get {
                object obj = ResourceManager.GetObject("EditPasteMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditPasteSpecialMenu {
            get {
                object obj = ResourceManager.GetObject("EditPasteSpecialMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditUndoMenu {
            get {
                object obj = ResourceManager.GetObject("EditUndoMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileExitMenu {
            get {
                object obj = ResourceManager.GetObject("FileExitMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileImportMenu {
            get {
                object obj = ResourceManager.GetObject("FileImportMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileNewMenu {
            get {
                object obj = ResourceManager.GetObject("FileNewMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileOpenMenu {
            get {
                object obj = ResourceManager.GetObject("FileOpenMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilePropertiesMenu {
            get {
                object obj = ResourceManager.GetObject("FilePropertiesMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSaveMenu {
            get {
                object obj = ResourceManager.GetObject("FileSaveMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterAddRangeMenu {
            get {
                object obj = ResourceManager.GetObject("FilterAddRangeMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterAddTextMenu {
            get {
                object obj = ResourceManager.GetObject("FilterAddTextMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterBuilderMenu {
            get {
                object obj = ResourceManager.GetObject("FilterBuilderMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterButton {
            get {
                object obj = ResourceManager.GetObject("FilterButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterShowAllMenu {
            get {
                object obj = ResourceManager.GetObject("FilterShowAllMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpAboutMenu {
            get {
                object obj = ResourceManager.GetObject("HelpAboutMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpBuyProgramMenu {
            get {
                object obj = ResourceManager.GetObject("HelpBuyProgramMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpHomePageMenu {
            get {
                object obj = ResourceManager.GetObject("HelpHomePageMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpManualMenu {
            get {
                object obj = ResourceManager.GetObject("HelpManualMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpRegisterMenu {
            get {
                object obj = ResourceManager.GetObject("HelpRegisterMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpSuggestionsMenu {
            get {
                object obj = ResourceManager.GetObject("HelpSuggestionsMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpSupportMenu {
            get {
                object obj = ResourceManager.GetObject("HelpSupportMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchNewMenu {
            get {
                object obj = ResourceManager.GetObject("SearchNewMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchNextMenu {
            get {
                object obj = ResourceManager.GetObject("SearchNextMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchPreviousMenu {
            get {
                object obj = ResourceManager.GetObject("SearchPreviousMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchReplaceMenu {
            get {
                object obj = ResourceManager.GetObject("SearchReplaceMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchSearchMenu {
            get {
                object obj = ResourceManager.GetObject("SearchSearchMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsAutoUpdateMenu {
            get {
                object obj = ResourceManager.GetObject("ToolsAutoUpdateMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsCustomFieldsMenu {
            get {
                object obj = ResourceManager.GetObject("ToolsCustomFieldsMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsPromoSmsMenu {
            get {
                object obj = ResourceManager.GetObject("ToolsPromoSmsMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsSettingsMenu {
            get {
                object obj = ResourceManager.GetObject("ToolsSettingsMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsTestSystemMenu {
            get {
                object obj = ResourceManager.GetObject("ToolsTestSystemMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
